# Description

## Description du data set
- Les données sont décomposées en 3 datasets (Train, Validation, Test)
- Chaque ligne représente une question, et 5 réponses au choix. Une seule réponse correct par question
- La colonne "correct_answers" est la validation de la bonne réponse (allant de 0 à 4)

In [2]:
from google.cloud import storage
from datasets import load_from_disk
import gcsfs
import pandas as pd

# # Authentification (si pas déjà fait)
# from google.colab import auth
# auth.authenticate_user()

c:\Users\Fabien\Desktop\OC\P14\FINE-TUNING_MEDICAL\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# Chargement direct depuis le bucket, sans copie locale
dataset = load_from_disk("gs://p14-medical-data/raw_data/frenchmedmcqa_dataset/")
# Vérification rapide
print(dataset)
print(dataset["train"][0])  # Premier exemple

DatasetDict({
    train: Dataset({
        features: ['id', 'question', 'answer_a', 'answer_b', 'answer_c', 'answer_d', 'answer_e', 'correct_answers', 'number_correct_answers'],
        num_rows: 595
    })
    validation: Dataset({
        features: ['id', 'question', 'answer_a', 'answer_b', 'answer_c', 'answer_d', 'answer_e', 'correct_answers', 'number_correct_answers'],
        num_rows: 164
    })
    test: Dataset({
        features: ['id', 'question', 'answer_a', 'answer_b', 'answer_c', 'answer_d', 'answer_e', 'correct_answers', 'number_correct_answers'],
        num_rows: 321
    })
})
{'id': '230bac49b0fe863b772410bc8d01a025f63c3c999065480131d6334abd2efeff', 'question': 'Parmi les affirmations suivantes, une seule est fausse, indiquer laquelle: les particules alpha', 'answer_a': "Sont formées de noyaux d'hélium", 'answer_b': 'Sont peu pénétrantes', 'answer_c': "Toute l'énergie qu'elles transportent est cédée au long d'un parcours de quelques centimètres dans l'air", 'answer_d': 'Sont arrêtées par une feuille de papier', 'answer_e': 'Sont peu ionisantes', 'correct_answers': 4, 'number_correct_answers': 0}

# Analysis dataset

## Exploration dataset train

In [4]:
df = pd.DataFrame(dataset["train"])
df.head(5)

,id,question,answer_a,answer_b,answer_c,answer_d,answer_e,correct_answers,number_correct_answers
0,230bac49b0fe863b772410bc8d01a025f63c3c99906548...,"Parmi les affirmations suivantes, une seule es...",Sont formées de noyaux d'hélium,Sont peu pénétrantes,Toute l'énergie qu'elles transportent est cédé...,Sont arrêtées par une feuille de papier,Sont peu ionisantes,4,0
1,0ca718ff033bb68503e41c4d30b4f7580cb3f220e000a2...,"Parmi les bactéries suivantes, une seule ne pe...",Haemophilus influenzae,Streptococcus pneumoniae,Neisseria gonorrhoeae,Neisseria meningitidis,Mycobacterium tuberculosis,2,0
2,3e292fc26ab1844f7d3805a5cceba0534261fcd65446dc...,"Parmi les propositions suivantes, indiquer cel...",D'héroine,De cannabis,De cocaïne,D'amphétamines,De LSD (Amide de l'acide lysergique),2,0
3,6c35039202449b2b89e7b8a79dd0d7ae1b73ad65098844...,"Parmi les propositions suivantes, une seule es...",5-hydroxy tryptophane,5-hydroxy tryptamine,Dihydroxy phénylalanine,Dihydroxy tryptophane,"5,6-dihydroxytryptamine",1,0
4,dd39598f83a51258dc16cd37c21496ed298cf66b7245f8...,"Parmi les techniques voltampérométriques, on t...",La potentiométrie,La polarographie,La conductimétrie,l'ampérométrie,La coulométrie,1,0

In [5]:
df.describe(include='all')

,id,question,answer_a,answer_b,answer_c,answer_d,answer_e,correct_answers,number_correct_answers
count,595,595,595,595,595,595,595,595.000000,595.0
unique,594,592,574,576,572,578,541,NaN,NaN
top,04c58320a365b34e9e7fc96b9b969731265be6e71453cc...,"Parmi les propositions suivantes, quelle est c...",Il s'agit d'un virus à ARN,Il appartient à la famille des Hepadnaviridae,Il possède une enveloppe lipoprotéique,Erythromycine,Aucune de ces réponses n'est exacte,NaN,NaN
freq,2,2,3,3,3,3,33,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.028571,0.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.288720,0.0
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,0.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,0.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,0.0

In [6]:
df["correct_answers"].value_counts()

correct_answers
3    156
2    142
1    119
0     94
4     84
Name: count, dtype: int64

In [7]:
df.isna().sum()

id                        0
question                  0
answer_a                  0
answer_b                  0
answer_c                  0
answer_d                  0
answer_e                  0
correct_answers           0
number_correct_answers    0
dtype: int64

## Colonnes avec doublons

In [8]:
df[df.duplicated(keep=False)]

,id,question,answer_a,answer_b,answer_c,answer_d,answer_e,correct_answers,number_correct_answers
292,04c58320a365b34e9e7fc96b9b969731265be6e71453cc...,"Parmi les caractères suivants, lequel n'est pa...",Présence d'une capsule,Catalase négative,Survie en aérobiose et anaérobiose,Production d'une toxine de Panton-Valentine,Hémolytique sur gélose au sang,3,0
301,04c58320a365b34e9e7fc96b9b969731265be6e71453cc...,"Parmi les caractères suivants, lequel n'est pa...",Présence d'une capsule,Catalase négative,Survie en aérobiose et anaérobiose,Production d'une toxine de Panton-Valentine,Hémolytique sur gélose au sang,3,0

In [9]:
df[df.duplicated(subset=['question'])]

,id,question,answer_a,answer_b,answer_c,answer_d,answer_e,correct_answers,number_correct_answers
168,b8d72196ad0863e712a0a4fd827a0aae5773af49b04cfe...,"Parmi les propositions suivantes, quelle est c...",Tous les établissements de santé peuvent rétro...,Seuls les établissements de santé publics peuv...,Seuls les établissements autorisés peuvent rét...,Tous les médicaments peuvent être rétrocédés,Seuls les médicaments réservés à l'usage hospi...,2,0
293,0835a193cf102df1c723e22f929d29f511c7fc10c253d3...,"Parmi ces propositions, laquelle est fausse ?",Il existe une région homologue dans les gonoso...,Dans les maladies génétiques à transmission do...,Toutes les filles d'un homme atteint de maladi...,La transmission des maladies génétiques monogé...,Les ovocytes sont des cellules haploïdes.,3,0
301,04c58320a365b34e9e7fc96b9b969731265be6e71453cc...,"Parmi les caractères suivants, lequel n'est pa...",Présence d'une capsule,Catalase négative,Survie en aérobiose et anaérobiose,Production d'une toxine de Panton-Valentine,Hémolytique sur gélose au sang,3,0

**ATTENTION A L'INTERPRETATION DES QUESTIONS REPONSES COMME CELLES CI**

## Data Cleaning

In [10]:
df = df.drop(columns=["id", "number_correct_answers" ])

In [11]:
match_dict = {
    0 : "answer_a",
    1 : "answer_b",
    2 : "answer_c",
    3 : "answer_d",
    4 : "answer_e"
}
df['correct_answer_text'] = df['correct_answers'].map(match_dict)

In [12]:
df['answer'] = df.apply(lambda row: row[row['correct_answer_text']],axis=1)

In [13]:
df_cleaned = df.loc[:,['question', 'answer']]

In [14]:
df_cleaned.head()

                                            question                 answer
0  Parmi les affirmations suivantes, une seule es...    Sont peu ionisantes
1  Parmi les bactéries suivantes, une seule ne pe...  Neisseria gonorrhoeae
2  Parmi les propositions suivantes, indiquer cel...             De cocaïne
3  Parmi les propositions suivantes, une seule es...   5-hydroxy tryptamine
4  Parmi les techniques voltampérométriques, on t...       La polarographie

In [15]:
df_cleaned[df_cleaned.duplicated(keep=False)]

,question,answer
292,"Parmi les caractères suivants, lequel n'est pa...",Production d'une toxine de Panton-Valentine
301,"Parmi les caractères suivants, lequel n'est pa...",Production d'une toxine de Panton-Valentine

In [17]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
df_cleaned.head(100)

,question,answer
0,"Parmi les affirmations suivantes, une seule est fausse, indiquer laquelle: les particules alpha",Sont peu ionisantes
1,"Parmi les bactéries suivantes, une seule ne peut généralement pas être responsable d'une méningite aiguë, laquelle?",Neisseria gonorrhoeae
2,"Parmi les propositions suivantes, indiquer celle qui est exacte. Le crack est une forme:",De cocaïne
3,"Parmi les propositions suivantes, une seule est exacte. Laquelle? La sérotonine est le (la) :",5-hydroxy tryptamine
4,"Parmi les techniques voltampérométriques, on trouve:",La polarographie
5,"Concernant le misoprostol (CYTOTEC®), donner son mécanisme d'action:",Analogue des prostaglandines
6,Quelle est la proposition qui ne s'applique pas à la norfloxacine ?,Elle est utilisable pour le traitement des broncho-pneumopathies à bactérie sensible
7,"Parmi les propositions suivantes concernant la fluorimétrie, une seule proposition est fausse. Laquelle?",La fluorescence est un phénomène dont la durée est de l'ordre de la seconde
8,La sécrétion de progestérone pendant les 2e et 3e trimestres de la grossesse reflète l'état fonctionnel:,Du placenta
9,"Parmi les propositions suivantes, une seule est exacte; laquelle? L'hormone thyroïdienne la plus active au niveau cellulaire est:",La triiodothyronine (T3)
10,"Parmi les propositions suivantes concernant la qualité d'une séparation en HPLC entre deux constituants d'un mélange, laquelle est exacte? La qualité de la séparation est appréciée par:",Le facteur de résolution
11,"Parmi ces cinq propositions, indiquer le mode habituel de contamination de l'homme dans la bilharziose urinaire:",Pénétration trans-cutanée
12,"Parmi les propositions suivantes, indiquez la proposition exacte. Les moutardes à l'azote sont:",Des alkylants
13,"En photométrie de flamme, la qualité de nébulisation est indépendante:",De la température de la flamme
14,"Parmi les propositions suivantes, une seule est fausse. Laquelle? la bromocriptine :",A des propriétés anticholinergiques
15,Quelle est la proposition inexacte concernant les modifications des activités enzymatiques provoquées par le benzène?,Inhibition des monoxygénases Cytochrome P 450 dépendantes qui participent au métabolisme du benzène
16,Le syndrome de « cytolyse» hépatique est caractérisé par:,Une augmentation de la concentration sérique de l'alanine-amino transférase
17,Le prurit anal est le symptôme majeur de:,L'oxyurose
18,"Parmi les propositions suivantes, une seule est fausse, indiquez laquelle. Les sels biliaires :",Sont indispensables à l'absorption intestinale de constituants hydrosolubles
19,"Indiquer, parmi les caractères suivants, celui qui est commun à toutes les anémies arégénératives :",Réticulocytopénie
20,"Parmi les bactéries suivantes, laquelle est un agent habituel de méningite néonatale?",Streptococcus agalactiae .
21,"Parmi les propositions suivantes, quelle est celle qui s'applique à Mycobacterium tuberculosis ?",Il peut être responsable d'infections urinaires
22,Parmi les propositions suivantes concernant l'imipramine. laquelle est inexacte?,Ses effets cliniques se manifestent en 24 à 48h
23,"Parmi les propositions suivantes concernant les diurétiques, une seule est fausse. Laquelle?",La spironolactone (ALDACTONE) est souvent associée aux inhibiteurs de l'enzyme de conversion de l'angiotensine
24,"Parmi les anti-ulcéreux suivant, quel est celui qui possède, aux concentrations thérapeutiques, des propriétés inhibitrices des cytochromes P450 ?",Cimétidine
25,"Parmi les paramètres suivants, citer celui qui constitue un marqueur de l'ostéogénèse :",Ostéocalcine
26,Dans l'organisme quel est le milieu où les cyclines ne diffusent pas?,LCR
27,"Parmi les propositions, une seule est fausse. Laquelle? Un carbure de formule brute CnH2n:",Peut être un acétylénique
28,"Parmi les éléments suivants, quel est celui qui n'entre pas dans l'uréogenèse ?",Valine
29,"Parmi les propositions suivantes, indiquer celle qui exacte. L'indication habituelle du fluconazole (TRIFLUCAN®) est:",Les infections à levures
30,"Dans une des conditions suivantes, l'antigène est tolérogène, laquelle?",Administration par voie intra-veineuse
31,"Parmi les symptômes suivants, indiquer celui qui n'est pas observé lors d'une intoxication aiguë par le monoxyde de carbone",Cyanose
32,"Une gamma glutamyltransférase sérique élevée, associée à un volume globulaire moyen augmenté est évocatrice de :",Intoxication alcoolique chronique
33,"Parmi les propositions suivantes concernant le virus de l'immunodéficience humaine, laquelle est exacte?",Ils possèdent une enzyme capable de transcrire l'ARN en ADN
34,"Le catharomètre est un détecteur utilisé chromatographie en phase gazeuse. Parmi les propositions suivantes, laquelle est fausse?",Son fonctionnement repose sur l'ionisation des molécules
35,Parmi les propositions suivantes une seule est exacte. Laquelle? Une solution jaune absorbe dans une zone du spectre se situant:,Autour de 400 nm
36,"Parmi les neurotransmetteurs ou neuromodulateurs proposés, lequel intervient dans le mécanisme d'action des benzodiazépines?",Le GABA
37,"Parmi les propositions suivantes concernant l'amibiase, une seule est fausse. Laquelle?",Elle est due à Entamoeba dispar
38,"Parmi les mécanismes de l'action antibactérienne des fluoroquinolones, citez celui qui est exact",Inhibition de la réplication de l'ADN
39,"Parmi les propositions suivantes, une seule est fausse. Indiquez laquelle? La rifampicine:",Est un alcaloïde
40,"Parmi les propositions suivantes, une seule est fausse. Indiquez laquelle? L'haptoglobine plasmatique:",Augmente dans les insuffisances hépatocellulaires
41,"Parmi les propositions suivantes, une seule est exacte. Laquelle? Les inhibiteurs de l'enzyme de conversion de l'angiotensine I :",Diminuent la post-charge
42,"Parmi les propriétés bactériologiques et pharmacocinétiques suivantes, laquelle n'est pas une caractéristique des aminosides?",Forte liaison aux protéines plasmatiques
43,"Parmi les propositions suivantes concernant les antidotes et les antagonistes, une seule est fausse. Laquelle?",Les folates sont utilisés lors de l'intoxication par l'éthylène glycol
44,"Quelle méthode peut être utilisée pour déterminer la constante d'acidité (7,1 et 10,6) de l'acide valproïque (acide dipropylacétique) ?",La potentiométrie
45,"Parmi les propositions suivantes, une seule est exacte. Au cours de la leucémie lymphoïde chronique, le myélogramme montre:",Une population de lymphocytes>30%
46,"Parmi les enzymes suivantes, une seule n'intervient pas dans la cétogenèse. Laquelle?",Pyruvate kinase
47,"Parmi les propositions concernant la lithiase biliaire, une seule est fausse. Laquelle?",Elle évolue vers une cirrhose
48,"Parmi les propositions suivantes à propos de la vancomycine, laquelle est inexacte?",C'est une béta-lactammine
49,"L'effet tyramine à l'origine de crises hypertensives graves est rencontré fréquemment avec une classe de médicaments, laquelle?",Les inhibiteurs de la mono amine oxydase
50,"Parmi les propositions suivantes, une seule est fausse. Laquelle? Une hyperkaliurie est généralement observée au cours:",D'une acidose métabolique
51,"Parmi les propositions suivantes, une seule est exacte. Laquelle? Le traitement d'une intoxication aiguë par le méthanol consiste à administrer:",De l'éthanol
52,"Parmi les propositions suivantes, une seule est exacte. Laquelle? La potasse éthanolique 0,lN permet de doser:",Le phénobarbital
53,"Parmi les substances suivantes, une seule ne traverse pas la barrière placentaire. Laquelle?",Héparine
54,"Parmi les propositions suivantes, une seule est fausse. Indiquer laquelle? Les enzymes suivantes interviennent dans la digestion des lipides alimentaires:",Lipoprotéine lipase
55,"Parmi les affirmations suivantes concernant le virus de l'hépatite B,une seule est fausse.Laquelle ?",Il s'agit d'un virus à ARN
56,Sur laquelle de ses méthodes repose le diagnostic parasitologique directe de l'ankylostomose ?,La recherche d' oeufs dans les selles
57,Que se passe-t-il pendant la systole ventriculaire?,La contraction ventriculaire
58,"Parmi les propositions suivantes, une seule est exacte. Laquelle? L'aldostérone est secrétée par:",La zone glomérulée de la cortico-surrénale
59,"Parmi les propositions suivantes, une seule est fausse. Laquelle? L'AMPHOTERICINE B :",Agit spécifiquement sur les dermatophytes
60,Le taeniasis à Taenia saginata se contracte:,Par ingestion de viande de boeuf
61,"L'identification d'une levure impliquée dans une pathologie humaine nécessite la réalisation de tous ces tests, sauf un. Lequel?",Inoculation à l'animal
62,"Parmi les propositions suivantes, une seule est exacte. Laquelle? Le segment du tubule rénal strictement imperméable à l'eau est:",La branche ascendante de l'anse de Henlé
63,"Quel est le médicament qui, associé à un aminoside, expose à un risque cytotoxique?",Furosémide
64,Quelle(s) affirmation(s) est(sont) exacte(s) ? L'énergie d'activation d'une réaction enzymatique est:,L'énergie nécessaire pour activer le substrat
65,"En France, parmi les vaccinations suivantes, quelle(s) est (sont) celle(s) qui correspond(ent) à un vaccin vivant atténué disponible en France ? (actualisé 2008)",Vaccination anti-rubéolique
66,"Parmi les propositions suivantes concernant la loi de Beer-Lambert, indiquer la (les) proposition(s) exacte(s) :",Elle s'applique aux dosages spectrophotométriques
67,"D'après les articles législatifs du code de la santé publique, l'information relative à l'état de santé du patient :",Doit être transmise par le professionnel de santé qui doit s'assurer de la compréhension des informations et explications données
68,Une insuffisance rénale peut être causée par le :,L'éthylène glycol
69,Indiquez la ou les réponses exactes: Les lymphocytes B:,Possèdent un récepteur pour le virus Epstein-Barr
70,"Les 3 nucléides de l'hydrogène, H(A=1,Z=1), H(A=2,Z=1) et H(A=3,Z=1) sont:",Des isotopes
71,"Quelle est la protéine dont la concentration plasmatique, chez un sujet normal, est la plus élevée ?",Albumine
72,"Parmi ces effets des glucocorticoïdes utilisés au long cours, lequel est faux ?",Immunostimulation
73,"Parmi les propositions suivantes concernant la filtration stérilisante, une seule est inexacte, laquelle ?",Elle permet d'obtenir la stérilité des suspensions injectables de principes actifs thermosensibles
74,Quelle est la base qui n'existe pas dans une molécule d'ADN ?,Uracile
75,"Parmi les questions suivantes concernant la prévention, une seule est fausse. Laquelle ?",Le dépistage est une mesure de prévention primaire
76,Un patient de 20 ans est traité par héparine de bas poids moléculaire pour une thrombose iliaque. Il présente un syndrome hémorragique majeur. Parmi les résultats suivants le(s)quel(s) permet(tent) d'affirmer la présence d'un surdosage?,"Activité anti Xa = 2,00 UI/mL"
77,"Parmi les propositions suivantes, quel est l'antibiotique de choix pour traiter une infection à Listeria monocytogenes ?",Amoxicilline
78,"Parmi les médicaments suivants, lequel est contre-indiqué avec les sulfamides hypoglycémiants ?",Miconazole (DAKTARIN®)
79,"Parmi les propositions suivantes, laquelle est exacte ? Le mésusage est défini comme :",Une utilisation de médicament non conforme aux recommandations du résumé des caractéristiques du produit
80,"Parmi les propositions suivantes, quelle est celle qui est fausse ?",La méthode immunométrique dite sandwich fait appel à un seul anticorps
81,"Parmi les propositions suivantes, quelle est celle qui est exacte ? La certification des établissements de santé",Concerne tous les établissements de santé
82,La biodisponibilité absolue d'un médicament est obtenue en prenant comme référence:,L'aire sous la courbe après administration intraveineuse
83,"Parmi les affirmations suivantes concernant le virus de l'hépatite B, une seule est fausse. Laquelle ?",Il s'agit d'un virus à ARN
84,Parmi les propositions suivantes quelle est celle qui est fausse ?,La séparation de composés par chromatographie par échange d'ions sur résines carboxyliques est indépendante du pH
85,"Dans l'hémophilie B majeure, quel(s) test(s) est (sont) perturbé(s) parmi les suivants:",Temps de céphaline activée
86,Quel(s) est (sont) la (ou les) enzyme(s) dont le déficit entraîne une hémolyse lors de la prise de certains médicaments?,La glucose 6 phosphate déshydrogénase
87,"Dans une population de 1 million de personnes, 450 nouveaux cas d'une maladie sont diagnostiqués en une année, dont 300 cas chez les femmes. Cocher la ou les proposition(s) exacte(s) :",L'incidence annuelle est de 45/100 000
88,Indiquer quelle(s) est(sont) l'(les) indication(s) habituelle(s) du fluconazole :,Les infections à levures
89,"Parmi les propositions suivantes, laquelle (lesquelles) est (sont) exacte(s)? L'unité fonctionnelle de base du rein est:",Le néphron
90,"Parmi les parasitoses suivantes, dans laquelle n'observe-t-on jamais d'hépatomégalie ?",Giardiose
91,"Parmi les propositions suivantes, quelle est celle qui est exacte ?",Un complexe est dit parfait si les ions sont masqués à leurs réactifs habituels
92,Le mécanisme d'action des azolés sur la cellule fongique est :,L'inhibition de la biosynthèse de l'ergostérol
93,"Parmi les médicaments suivants, lequel peut provoquer une hémolyse en cas de déficit en glucose-6-phosphate déhydrogénase (G6PD) ?",cotrimoxazole (BACTRIM®)
94,"Parmi les germes suivants, un seul est sporulé. Lequel ?",Clostridium perfringens
95,"Parmi les propositions concernant l'oméprazole (MOPRAL®), une seule est inexacte laquelle ?",Il a un effet antisécrétoire limité (< 12 heures)
96,"Une seule de ces propositions est fausse, laquelle ? Plasmodium falciparum peut être responsable :",d'une néphrite quartane
97,"Parmi les propositions suivantes concernant les comprimés une seule est fausse, laquelle ?",L'enrobage par film est toujours réalisé en lit d'air fluidisé
98,"Lors du traitement d'une tuberculose, pour lequel de ces antibiotiques, sera-t-il nécessaire de vérifier la fonction oculaire ?",Ethambutol
99,"Parmi les propositions suivantes concernant le cytomégalovirus humain, une seule est fausse laquelle ?",Il produit un effet cytopathique après 24 heures de culture

# cleaned data Visualisation

In [37]:
pd.set_option('display.max_colwidth', False)

df = pd.read_parquet("gs://p14-medical-data/processed_data/frenchmedmcqa_dataset/frenchmedmcqa_train.parquet")
df.head()

                                                                                                              question                 answer
0  Parmi les affirmations suivantes, une seule est fausse, indiquer laquelle: les particules alpha                      Sont peu ionisantes
1  Parmi les bactéries suivantes, une seule ne peut généralement pas être responsable d'une méningite aiguë, laquelle?  Neisseria gonorrhoeae
2  Parmi les propositions suivantes, indiquer celle qui est exacte. Le crack est une forme:                             De cocaïne
3  Parmi les propositions suivantes, une seule est exacte. Laquelle? La sérotonine est le (la) :                        5-hydroxy tryptamine
4  Parmi les techniques voltampérométriques, on trouve:                                                                 La polarographie