# Description

## Description du dataset

In [2]:
from google.cloud import storage
from datasets import load_from_disk
import gcsfs
import pandas as pd

c:\Users\Fabien\Desktop\OC\P14\FINE-TUNING_MEDICAL\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
medquad_dataset = load_from_disk("gs://p14-medical-data/raw_data/MedQuad_dataset/")

# Analyse dataset

## Exploration dataset mcqm

In [5]:
df_medquad = pd.DataFrame(medquad_dataset['train'])
df_medquad.head()

,qtype,Question,Answer
0,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...
1,symptoms,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...
2,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...
3,exams and tests,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos..."
4,treatment,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen..."

In [6]:
df_medquad.describe()

,qtype,Question,Answer
count,16407,16407,16407
unique,16,14979,15817
top,information,What causes Causes of Diabetes ?,This condition is inherited in an autosomal re...
freq,4535,20,348

In [9]:
df_medquad[df_medquad.duplicated(keep=False)]

,qtype,Question,Answer
1387,information,What is (are) Hypoglycemia ?,"Hypoglycemia, also called low blood glucose or..."
1388,information,What is (are) Hypoglycemia ?,"Hypoglycemia, also called low blood glucose or..."
1389,symptoms,What are the symptoms of Hypoglycemia ?,Hypoglycemia causes symptoms such as\n ...
1390,symptoms,What are the symptoms of Hypoglycemia ?,Hypoglycemia causes symptoms such as\n ...
1391,causes,What causes Hypoglycemia ?,Diabetes Medications\n \nHypogl...
...,...,...,...
2288,information,What is (are) Kidney Failure: Eat Right to Fee...,"Before you were on dialysis, your doctor may h..."
2289,information,What is (are) Kidney Failure: Eat Right to Fee...,Sodium is found in salt and other foods. Most ...
2290,information,What is (are) Kidney Failure: Eat Right to Fee...,Sodium is found in salt and other foods. Most ...
2291,information,What is (are) Kidney Failure: Eat Right to Fee...,Calories provide energy for your body. If your...
2292,information,What is (are) Kidney Failure: Eat Right to Fee...,Calories provide energy for your body. If your...

In [14]:
df_medquad=df_medquad.drop_duplicates()

In [15]:
df_medquad.describe()

,qtype,Question,Answer
count,16359,16359,16359
unique,16,14979,15817
top,information,What is (are) High Blood Cholesterol ?,This condition is inherited in an autosomal re...
freq,4520,19,348