# Description

## Description du dataset
Data set de prompt et réponse formulé par une IA

In [2]:
from google.cloud import storage
from datasets import load_from_disk
import gcsfs
import pandas as pd

c:\Users\Fabien\Desktop\OC\P14\FINE-TUNING_MEDICAL\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
ultraMed_Dataset = load_from_disk("gs://p14-medical-data/raw_data/UltraMedical_dataset")

# Analyse dataset

## Exploration dataset mcqm

In [4]:
df_ultraMed = pd.DataFrame(ultraMed_Dataset["train"])
df_ultraMed.head()

,prompt_id,label_type,prompt,chosen,rejected,metadata,feedback
0,"WikiInstruct,8304",length,Investigate the intricacies of immunometabolis...,[{'content': 'Investigate the intricacies of i...,[{'content': 'Investigate the intricacies of i...,{'chosen': {'evaluation': 'This response is ex...,Assistant A provides a detailed and comprehens...
1,"WikiInstruct,8846",length,Examine the differential immunotoxic effects e...,[{'content': 'Examine the differential immunot...,[{'content': 'Examine the differential immunot...,{'chosen': {'evaluation': 'This response effec...,"Assistant A's response is well-structured, pro..."
2,"MedMCQA,11404",length,A lady comes with melanotic pigmentation of li...,[{'content': 'A lady comes with melanotic pigm...,[{'content': 'A lady comes with melanotic pigm...,{'chosen': {'evaluation': 'The response is det...,Both Assistant A and Assistant B provided answ...
3,"ChatDoctor,33567",easy,my daughter was diagnosed with a liver cyst th...,[{'content': 'my daughter was diagnosed with a...,[{'content': 'my daughter was diagnosed with a...,{'chosen': {'evaluation': 'The response offers...,Assistant A provides a comprehensive and detai...
4,"WikiInstruct,14624",length,Investigate the physiological mechanisms under...,[{'content': 'Investigate the physiological me...,[{'content': 'Investigate the physiological me...,{'chosen': {'evaluation': 'The response is det...,Both Assistant A and Assistant B provide detai...

In [5]:

df_ultraMed["nb_message"] = df_ultraMed["chosen"].apply(len)

In [6]:
df_ultraMed["nb_message"].value_counts()

nb_message
2    109353
Name: count, dtype: int64

In [ ]:
df_ultraMed.describe(include='all')

In [1]:
import pandas as pd
from pathlib import Path

import os
BASE_DIR = Path(os.getcwd()).parents[1]
pd.set_option('display.max_colwidth', False)
pd.set_option('display.max_rows', None)
df = pd.read_parquet(BASE_DIR / "data" / "processed" / "ultramed_dataset" / "ultramed.parquet")
df.head(100)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      question  \
0   Investigate the intricacies of immunometabolism, a distinct subfield of immunology that examines the interconnection between cellular metabolic processes and the functional attributes of immune cells. Clarify the mechanisms by which this symbiosis modulates the comprehensive immune response, and analyze its integration within the broader spectrum of immunological studies, with an emphasis on the implications for metabolic diseases and the consequential effects on the proficiency of the immune system.
1   Examine the differential immunotoxic effects exerted by distinct microplastic polymer varieties on the innate and adaptive immune mechanisms across a range of marine organisms, emphasizing the plausible perturbations within their intracellular communication networks, and delineate the consequent alterations in cytokine profiles.
2   A lady comes with melanotic pigmentation of lip, presence of multiple polyps in the intestine, and a positive family history. What is the most probable diagnosis?\n\nA. Peutz-Jegher's Syndrome\nB. Gardner's syndrome\nC. Turcot's syndrome\nD. Lynch syndrome
3   my daughter was diagnosed with a liver cyst that is about the size of a large melon. Have you experienced a cyst this large before. She was rushed to ICU for treatment. her  blood glucose was way down and she need blood transfusions to bring it back up which was initially rejected by her body. She was then given plasma. After this an incision was made and a tube was inserted to drain the cyst. We were told that it is a miracle that with it being this large that it did not burst. We were also told that it will be touch and go for a while, and that she will be hospitalized for at least 3 weeks. What is  your opinion on this matter?
4   Investigate the physiological mechanisms underlying the blood-brain barrier's selective permeability, focusing on its role in protecting neural tissue from pathogenic organisms and neurotoxic substances. Expand this exploration by assessing how this barrier regulates the entry and exit of essential metabolites, particularly in the context of neurodegenerative diseases where this regulation may be compromised.
5   A 22-year-old medical student presents to a community health center due to an episode of loss of consciousness 3 days ago. She also has a history of multiple episodes of dizziness in the last year. These episodes almost always occur when she is observing surgery in the operating room. She describes her dizziness as a feeling of lightheadedness, warmth, excessive sweating, and palpitations. She feels that she will fall down if she stood longer and usually sits on the floor or leaves the room until the feeling subsides. Three days ago, she collapsed while observing an open cholecystectomy but regained consciousness after a few seconds. Once she regained consciousness, she was pale and sweating excessively. Her medical history is significant for migraines, but she is not on prophylactic therapy. Her younger brother has cerebral palsy, and her uncle had a sudden death at the age of 25. Her blood pressure is 120/80 mm Hg when lying down and 118/80 mm Hg when in a standing position. The rest of the physical examination is within normal limits. What is the next best step in the management of this patient?\n\nA. Echocardiogram\nB. Electrocardiogram (ECG)\nC. Electroencephalogram (EEG)\nD. Psychiatric evaluation for anxiety
6   For a 55-year-old female patient with a high index of suspicion for uterine-confined carcinoma, who has undergone preoperative imaging suggestive of non-metastatic disease, which of the following interventions would enable assessment of potential lymphatic dissemination while concurrently maintaining ovarian hormonal function, provided that the patient has a strong desire to retain ovarian endocrine activity post-procedure?\n\nA. Comprehensive pelvic lymphadenectomy without sentinel node identification, with a high risk of compromising ovarian hormonal function\nB. Peri-cervical injection of indocyanine green dye with subsequent immunofluorescence sentinel lymph node detection, while preserving ovarian structures\nC. Foregoing lymph node evaluation based on the definitive nature of imaging, with an emphasis on preserving endocrine ovarian function\nD. Commencing immediate platinum-based chemotherapy without assessing lymph nodes, which does not prioritize ovarian endocrine preservation
7   In a 50-year-old woman with a history of oral contraceptive use, presenting with jaundice, pruritus, and dark urine, who has elevated serum bilirubin and alkaline phosphatase levels, no history of alcohol or IV drug use, and a family history of liver transplantation due to an unspecified cause, which condition is most consistent with her presentation when also considering the presence of antimitochondrial antibodies?\n\nA. Primary biliary cirrhosis with presence of antimitochondrial antibodies and exclusion of viral hepatitis markers\nB. Graft-versus-host disease in the context of a non-hepatic organ transplant and absence of donor-specific antibodies\nC. Neonatal jaundice with maternal-fetal blood group incompatibility and a negative Coombs test\nD. Primary sclerosing cholangitis with concurrent inflammatory bowel disease and normal IgG4 levels
8   A 21-year-old man comes to the military base physician for evaluation of progressive discomfort in his right shoulder for the past 4 months. He joined the military 6 months ago and is part of a drill team. In anticipation of an upcoming competition, he has been practicing rifle drills and firing exercises 8 hours a day. Physical examination shows tenderness to palpation and a firm mass in the superior part of the right deltopectoral groove. Range of motion is limited by pain and stiffness. Which of the following is the most likely diagnosis?\n\nA. Osteoid osteoma\nB. Lipoma\nC. Acromioclavicular joint separation\nD. Myositis ossificans
9   A 52 year old female complains of sudden visual abnormalities. Her history reveals a 30 pack-year history of smoking, hypeension, and hypercholesterolemia. A head CT shows a lesion in the right occipital lobe and an angiogram reveals an embolic stroke of the right posterior cerebral aery. What type of visual deficit is she most likely experiencing?\n\nA. Bitemporal hemianopia\nB. Central scotoma\nC. Left homonymous hemianopia\nD. Left superior quadrantanopia
10  A 29-year-old woman, gravida 1, para 1, comes to the physician for the evaluation of a painful mass in her left breast for several days. She has no fevers or chills. She has not noticed any changes in the right breast. She has no history of serious illness. Her last menstrual period was 3 weeks ago. She appears anxious. Her temperature is 37°C (98.6°F), pulse is 80/min, respirations are 13/min, and blood pressure is 130/75 mm Hg. Examination shows a palpable, mobile, tender mass in the left upper quadrant of the breast. Ultrasound shows a 1.75-cm, well-circumscribed anechoic mass with posterior acoustic enhancement. The patient says that she is very concerned that she may have breast cancer and wishes further diagnostic testing. Which of the following is the most appropriate next step in the management of this patient?\n\nA. Fine needle aspiration\nB. Mammogram\nC. MRI scan of the left breast\nD. Core needle biopsy
11  In a 30-year-old male presenting with oligospermia and asthenozoospermia, which specific hormone, pivotal for the induction of testosterone synthesis within Leydig cells, should be quantified to assess the functionality of these cells, particularly considering the hypothalamic-pituitary-gonadal axis?\n\nA. Estrogen\nB. Follicle-stimulating hormone (FSH)\nC. Prolactin (PRL)\nD. Luteinizing hormone (LH)
12  Context: To demonstrate that interference microscopy of flat mounted internal limiting membrane specimens clearly delineates cellular proliferations at the vitreomacular interface.\nContext: ILM specimens harvested during vitrectomy were fixed in glutaraldehyde 0.05% and paraformaldehyde 2% for 24 h (pH 7.4). In addition to interference microscopy, immunocytochemistry using antibodies against glial fibrillar acidic protein (GFAP) and neurofilament (NF) was performed. After washing in phosphate-buffered saline 0.1 M, the specimens were flat-mounted on glass slides without sectioning, embedding or any other technique of conventional light microscopy. A cover slide and 4',6-diamidino-2-phenylindole (DAPI) medium were added to stain the cell nuclei.\nContext: Interference microscopy clearly delineates cellular proliferations at the ILM. DAPI stained the cell nuclei. Areas of cellular proliferation can be easily distinguished from ILM areas without cells. Immunocytochemistry can be performed without changing the protocols used in conventional microscopy.\nDoes interference microscopy delineate cellular proliferations on flat mounted internal limiting membrane specimens?\n\nA. yes\nB. no\nC. maybe
13  A 34-year-old woman comes to the emergency department because of a 2-hour history of abdominal pain, nausea, and vomiting that began an hour after she finished lunch. Examination shows abdominal guarding and rigidity; bowel sounds are reduced. Magnetic resonance cholangiopancreatography shows the dorsal pancreatic duct draining into the minor papilla and a separate smaller duct draining into the major papilla. The spleen is located anterior to the left kidney. A disruption of which of the following embryological processes is the most likely cause of this patient's imaging findings?\n\nA. Fusion of the pancreatic buds\nB. Rotation of the midgut\nC. Proliferation of mesenchyme in the dorsal mesentery\nD. Differentiation of the proximal hepatic diverticulum
14  In a 67-year-old male smoker with COPD and current signs of systemic infection alongside radiographic lung abnormalities, which cell lineage, upon stimulation by specific granulocyte CSFs, is chiefly tasked with initiating an innate immune defense in the alveoli?\n\nA. Myeloid lineage cells\nB. Circulating erythroid cells\nC. Liver parenchymal cells\nD. Adipose tissue-derived cells
15  In subjects manifesting compromised immunological responses, elucidate the augmented propensity for adverse reactions when exposed to exogenous compounds, including pharmacological formulations, ecological pollutants, and allergens, detailing the ramifications of such heightened sensitivity due to dysfunctional immune mechanisms.
16  Acalculous cholecystitis can be seen in all the following conditions except -\n\nA. Enteric fever\nB. Dengue haemorrhagic fever\nC. Leptospirosis .\nD. Malaria
17  At a 6-month check-up, an infant with no family history of neuromuscular diseases presents with hypotonia and spastic diplegia. The pediatrician notes a sustained extension and adduction of the legs when lifted by the axillae, and a bilaterally positive Babinski sign. Which diagnosis is most consistent with these findings, taking into account the infant's age, symptoms, and family history?\n\nA. Cerebral palsy with diplegia\nB. Acute flaccid myelitis\nC. Spinal muscular atrophy\nD. Normal developmental variation
18  In the context of a normal vaginal delivery, when an episiotomy is deemed necessary by the attending obstetrician, at what precise moment is it customarily performed, considering the maternal position, fetal head presentation, and stage of labor?\n\nA. At the onset of the second stage of labor, prior to the fetal head's visibility, while the mother is in the upright position, but after full cervical dilation.\nB. Immediately after the amniotic sac ruptures, irrespective of the fetal head's visibility, with the mother in the lithotomy position during the first stage of labor.\nC. When the fetal head is visible at a diameter of 4 cm during a contraction, indicating crowning, with the mother in a birthing chair, during the transition phase.\nD. When the fetal head is visible at a diameter of 2 cm during a contraction, with the mother in a semi-recumbent position at the peak of the second stage.
19  In an analytical synopsis derived from 'Obstetrics_Williams' that evaluates the differential prevalence of hypertensive complications in monozygotic versus dizygotic twin pregnancies, with a specific focus on the role of chorionicity and the additional factor of the twins' zygosity concordance, which outcome is the study likely to report?\n\nA. The genetic variability inherent in dizygotic twins is associated with a heightened occurrence of hypertensive complications, with both chorionicity and zygosity concordance playing a role.\nB. Monozygotic and dizygotic twins exhibit an equivalent frequency of hypertensive complications when chorionicity and zygosity concordance are both accounted for.\nC. Monozygotic twins, especially those with monochorionic placentation, have an escalated incidence of hypertensive complications, also considering zygosity concordance.\nD. Compared to singleton gestations, twin pregnancies are less prone to hypertensive complications when both chorionicity and zygosity concordance are evaluated.
20  I had thyroid cancer years ago and had a thyroidectomy and radiation ablation. I was on Synthroid 150mg for years, after menopause my doctor lowered my dosage and I became symptomatic, cold hands, dry skin, and weight gain of 12 lbs in less than 6 months ( I watch my weight and have maintained the same wt for 10 years and I haven t changed my diet or exercise.) He added Cytomel 5mg once daily at my urging the cold intolerance is slightly better, but not cured my hands are still cold and I am still too cold to get into the pool most days, my question is about the Cytomel dose. I have been doing some studying and most the literature calls for a dose in morning and one at night I was wondering if this would help my symptoms since I have had some improvement but not much. I have stopped the weight gain, but I have not lost the extra pounds I put on during the change. My thyroid levels are normal so my doctor has not changed the dosage, bu my symptoms are not. Thank you,
21  A doctor is treating a patient N% ith i;mike bite. He should not forget that viper verloril\n\nA. Histotoxic\nB. Vasculotoxic\nC. Musculotoxic\nD. Neurotoxic
22  Which of the following is the likely explanation for symmetrical uptake in bilateral supraclavicular areas with no uptake on paratracheal nodes on PET-CT in a patient with ca esophagus?\n\nA. Brown adipose tissue\nB. Paraneoplastic polymyositis\nC. Recent trauma\nD. Recent viral upper respiratory tract infection
23  All the following are true about Papilledema except-\n\nA. It is a purely non-inflammatory phenomenon\nB. Transient loss of vision occurs\nC. First sign is blurring of the nasal side of the optic disc\nD. Sudden loss of vision with painful eye movement
24  In a 6-month-old infant diagnosed with a large ventricular septal defect (VSD) and subsequent congestive heart failure (CHF), which pathophysiological mechanism is primarily responsible for the CHF, considering the additional factor of pulmonary vascular resistance beginning to normalize at this age and the effect on cardiac chamber pressures?\n\nA. Right-to-left shunting leading to systemic hypoxemia and decreased tissue oxygenation\nB. Obstruction of the pulmonary valve leading to increased afterload and right ventricular hypertrophy\nC. Stenosis of the aortic valve causing increased afterload and left ventricular hypertrophy\nD. Left-to-right shunting causing increased preload and volume overload in the right ventricle and pulmonary circulation
25  For a 69-year-old male with a recent ischemic stroke, aspirin allergy, and compromised cytochrome P450 2C19 activity, which antiplatelet agent should be prescribed, also considering a history of gastroesophageal reflux disease (GERD)?\n\nA. Prasugrel\nB. Ibuprofen\nC. Ticagrelor\nD. Naproxen
26  What are the genetic changes related to mandibulofacial dysostosis with microcephaly ?
27  A healthy 30-year-old woman comes to the physician with her husband for preconception counseling. Her husband is healthy but she is concerned because her brother was recently diagnosed with a genetic liver condition for which he takes penicillamine. Her father-in-law has liver cirrhosis and a tremor. The results of genetic testing show that both the patient and her husband are carriers of a mutation in the ATP7B gene. Which of the following is the chance that this patient’s offspring will eventually develop the hereditary condition?\n\nA. 0%\nB. 100%\nC. 25%\nD. 50%
28  Rewrite the given text making it suitable and easily understandable for an 8th-grade student.\n\nThe epidemiological evidence suggests that individuals with a higher caloric intake from saturated fats and trans fats suffer chronically from higher systemic inflammation.
29  Given a dataset derived from single-cell RNA sequencing that encompasses a diverse array of cell types, among which a particular subset is marked by a distinct genetic anomaly, deduce the likely impact of this specific genetic deviation on the cellular mechanisms. Utilize the single-cell RNA-seq data as the foundational basis for your analysis, ensuring to consider the gene expression profiles' alteration as a direct consequence of the aberration.
30  Examine the mechanisms by which enduring inflammatory conditions induce alterations in immune signaling pathways, leading to a diverse array of pathological conditions, and detail the subsequent impacts on cellular and systemic health outcomes.
31  Develop an integrative assessment framework that incorporates a cutting-edge biomarker analysis to quantify the therapeutic impact of a targeted epigenetic strategy aimed at slowing cellular aging, ensuring that the biomarker reflects both genetic and epigenetic changes.