In [12]:
from pathlib import Path
ROOT_DIR = Path().resolve().parent.parent

In [13]:
# quantization_config = BitsAndBytesConfig(load_in_4bit=True,bnb_4bit_quant_type="nf4", bnb_4bit_use_double_quant=True,bnb_4bit_compute_dtype=torch.bfloat16)
# model_4bit = AutoModelForCausalLM.from_pretrained("Qwen/Qwen3-1.7B-Base",quantization_config=quantization_config, dtype="auto", device_map="auto")

In [14]:
# with open(ROOT_DIR / "params.yaml", "r") as f:
#     config = yaml.safe_load(f)['lora_config']

# lora_config = LoraConfig(
#     task_type=config['task_type'],
#     r=config['r'],
#     lora_alpha=config['lora_alpha'],
#     lora_dropout=config['lora_dropout'],
#     target_modules=config['target_modules']
# )

# model = get_peft_model(model_4bit, lora_config)
# model.print_trainable_parameters()

In [15]:
import pandas as pd
df = pd.read_parquet(ROOT_DIR / "data/processed/sft_dataset/sft_train.parquet")
df.head()

,question,answer,medical_subject,has_clinical_case,language,question_type,confidence_level,dataset_name,token_count_question,token_count_answer
0,what is (are) prune belly syndrome ?,"prune belly syndrome, also called eagle-barret...",NaN,None,en,open_qa,high,medquad,9,191
1,what is (are) tietze syndrome ?,tietze syndrome is an inflammatory condition c...,NaN,None,en,open_qa,high,medquad,10,147
2,a <DATE> man from chile comes to the physician...,the patient's presentation includes a history ...,NaN,None,en,conversational,low,ultramed,195,383
3,"what are the symptoms of <LOCATION>, grebe type ?","what are the signs and symptoms of <LOCATION>,...",NaN,None,en,open_qa,high,medquad,12,545
4,in a patient with sle and concurrent mild live...,\n\nthe patient has sle (systemic lupus erythe...,NaN,None,en,conversational,low,ultramed,46,210

In [16]:
df.describe(include='all')

,question,answer,medical_subject,has_clinical_case,language,question_type,confidence_level,dataset_name,token_count_question,token_count_answer
count,3499,3499,875,875,3499,3499,3499,3499,3499.000000,3499.000000
unique,3461,3347,32,2,2,3,3,4,NaN,NaN
top,what are the genetic changes related to <PERSO...,<PERSON>,Cardiology,False,en,mcq_single,medium,medquad,NaN,NaN
freq,5,54,66,496,1940,1559,1559,970,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.594456,202.027722
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.144470,263.670832
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,1.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,9.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.000000,80.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.000000,330.500000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,781.000000,3419.000000