In [1]:
from pathlib import Path

ROOT_DIR = Path().resolve().parent.parent

In [13]:
# quantization_config = BitsAndBytesConfig(load_in_4bit=True,bnb_4bit_quant_type="nf4", bnb_4bit_use_double_quant=True,bnb_4bit_compute_dtype=torch.bfloat16)
# model_4bit = AutoModelForCausalLM.from_pretrained("Qwen/Qwen3-1.7B-Base",quantization_config=quantization_config, dtype="auto", device_map="auto")

In [14]:
# with open(ROOT_DIR / "params.yaml", "r") as f:
#     config = yaml.safe_load(f)['lora_config']

# lora_config = LoraConfig(
#     task_type=config['task_type'],
#     r=config['r'],
#     lora_alpha=config['lora_alpha'],
#     lora_dropout=config['lora_dropout'],
#     target_modules=config['target_modules']
# )

# model = get_peft_model(model_4bit, lora_config)
# model.print_trainable_parameters()

In [2]:
import pandas as pd
df = pd.read_parquet(ROOT_DIR / "data/processed/dpo_dataset/dpo_train.parquet")
df.head()

,question,chosen,rejected,language,question_type,confidence_level,dataset_name,token_count_question,token_count_chosen,token_count_rejected
0,employ isotopic signatures to infer the fluctu...,analyzing isotopic signatures from archaeologi...,to understand the dietary practices of mesolit...,en,conversational,low,ultramed,73,719,624
1,treatment of choice in saddle nose is?\n\na. a...,saddle nose is a condition where there is a no...,saddle nose deformity is a condition where th...,en,conversational,low,ultramed,22,234,233
2,"good afternoon, i have been experiencing numbn...",i'm sorry to hear about the discomfort you're ...,"i am not a doctor, but i can provide you with...",en,conversational,low,ultramed,184,471,326
3,context: the objective of this systematic revi...,\n\nthe question asks if the tissue engineerin...,let's break down the question and the context ...,en,conversational,low,ultramed,310,173,217
4,during the luteal phase of the menstrual cycle...,during the luteal phase of the menstrual cycle...,\n\nduring the luteal phase of the menstrual c...,en,conversational,low,ultramed,108,353,114

In [3]:
df.describe(include='all')

,question,chosen,rejected,language,question_type,confidence_level,dataset_name,token_count_question,token_count_chosen,token_count_rejected
count,3499,3499,3499,3499,3499,3499,3499,3499.000000,3499.000000,3499.000000
unique,3478,3497,3497,1,1,1,1,NaN,NaN,NaN
top,what are the genetic changes related to legius...,to deduce the likely enzymatic activity exhibi...,i'm so sorry to hear that you're still experie...,en,conversational,low,ultramed,NaN,NaN,NaN
freq,2,2,2,3499,3499,3499,3499,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.138039,455.161761,399.444984
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.439881,229.335218,241.475122
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,43.000000,6.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.000000,272.000000,201.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.000000,402.000000,331.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.000000,649.000000,594.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,656.000000,1758.000000,1800.000000